BASE_URL = "https://stellarburgers.education-services.ru/"
REGISTER_URL = "https://stellarburgers.education-services.ru/register"
AUTHORIZATION_URL = "https://stellarburgers.education-services.ru/login"
FORGOT_PASSWORD_URL = "https://stellarburgers.education-services.ru/forgot-password"
PERSONAL_ACCOUNT = "https://stellarburgers.education-services.ru/account/profile"